In [26]:
import os
import numpy as np


In [27]:
path_env = r"C:\Users\84440\Desktop\Env\ICML\subtask-graph-execution-master\sge\data\subtask_graph_mining\mining_train_1.npy"

In [28]:
X = np.load(path_env,allow_pickle=True)

In [30]:
len(X)

200

In [31]:
X.shape

(200,)

In [32]:
len(X[0])

6

In [33]:
X[0] # 'ORmat', 'rmag','W_o','W_a', 'ANDmat' ,'trind'

{'ORmat': array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
     

In [35]:
len(X[0]['trind'])

18

In [52]:
for i in X:
    print("len(i['trind']):" + str(len(i['trind'])) + ", len(i['rmag']:" + str(len(i['rmag'])))

len(i['trind']):18, len(i['rmag']:18
len(i['trind']):19, len(i['rmag']:19
len(i['trind']):19, len(i['rmag']:19
len(i['trind']):23, len(i['rmag']:23
len(i['trind']):15, len(i['rmag']:15
len(i['trind']):23, len(i['rmag']:23
len(i['trind']):24, len(i['rmag']:24
len(i['trind']):21, len(i['rmag']:21
len(i['trind']):21, len(i['rmag']:21
len(i['trind']):17, len(i['rmag']:17
len(i['trind']):18, len(i['rmag']:18
len(i['trind']):16, len(i['rmag']:16
len(i['trind']):16, len(i['rmag']:16
len(i['trind']):22, len(i['rmag']:22
len(i['trind']):23, len(i['rmag']:23
len(i['trind']):13, len(i['rmag']:13
len(i['trind']):11, len(i['rmag']:11
len(i['trind']):23, len(i['rmag']:23
len(i['trind']):19, len(i['rmag']:19
len(i['trind']):18, len(i['rmag']:18
len(i['trind']):21, len(i['rmag']:21
len(i['trind']):17, len(i['rmag']:17
len(i['trind']):20, len(i['rmag']:20
len(i['trind']):22, len(i['rmag']:22
len(i['trind']):24, len(i['rmag']:24
len(i['trind']):15, len(i['rmag']:15
len(i['trind']):17, len(i['rmag']:17
l

In [54]:
len(X[0]['W_a'])


9

In [49]:
len(X[0]['W_o'])

9

In [57]:
for i in X:
    print("len(i['W_a']):" + str(len(i['W_a'])) + ", len(i['ORmat']:" + str(len(i['ORmat'])))

len(i['W_a']):9, len(i['ORmat']:18
len(i['W_a']):9, len(i['ORmat']:19
len(i['W_a']):8, len(i['ORmat']:19
len(i['W_a']):9, len(i['ORmat']:23
len(i['W_a']):5, len(i['ORmat']:15
len(i['W_a']):9, len(i['ORmat']:23
len(i['W_a']):9, len(i['ORmat']:24
len(i['W_a']):9, len(i['ORmat']:21
len(i['W_a']):9, len(i['ORmat']:21
len(i['W_a']):8, len(i['ORmat']:17
len(i['W_a']):8, len(i['ORmat']:18
len(i['W_a']):7, len(i['ORmat']:16
len(i['W_a']):8, len(i['ORmat']:16
len(i['W_a']):9, len(i['ORmat']:22
len(i['W_a']):9, len(i['ORmat']:23
len(i['W_a']):7, len(i['ORmat']:13
len(i['W_a']):5, len(i['ORmat']:11
len(i['W_a']):9, len(i['ORmat']:23
len(i['W_a']):9, len(i['ORmat']:19
len(i['W_a']):8, len(i['ORmat']:18
len(i['W_a']):9, len(i['ORmat']:21
len(i['W_a']):8, len(i['ORmat']:17
len(i['W_a']):9, len(i['ORmat']:20
len(i['W_a']):9, len(i['ORmat']:22
len(i['W_a']):9, len(i['ORmat']:24
len(i['W_a']):6, len(i['ORmat']:15
len(i['W_a']):8, len(i['ORmat']:17
len(i['W_a']):9, len(i['ORmat']:23
len(i['W_a']):9, len

In [58]:
for i in X:
    print("i['ORmat']:" + str(i['ORmat']) + ", i['ANDmat']:" + str(i['ANDmat']))

i['ORmat']:[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]], i['ANDmat']:[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]
i['ORmat']:[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]], i['ANDmat']:[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0

In [66]:
for i in X:
    print("len(i['W_a']):" + str(len(i['W_a'])) + ", len(i['ANDmat']:" + str(len(i['ANDmat'])))

len(i['W_a']):9, len(i['ANDmat']:16
len(i['W_a']):9, len(i['ANDmat']:18
len(i['W_a']):8, len(i['ANDmat']:17
len(i['W_a']):9, len(i['ANDmat']:21
len(i['W_a']):5, len(i['ANDmat']:13
len(i['W_a']):9, len(i['ANDmat']:21
len(i['W_a']):9, len(i['ANDmat']:22
len(i['W_a']):9, len(i['ANDmat']:19
len(i['W_a']):9, len(i['ANDmat']:19
len(i['W_a']):8, len(i['ANDmat']:16
len(i['W_a']):8, len(i['ANDmat']:16
len(i['W_a']):7, len(i['ANDmat']:15
len(i['W_a']):8, len(i['ANDmat']:14
len(i['W_a']):9, len(i['ANDmat']:20
len(i['W_a']):9, len(i['ANDmat']:21
len(i['W_a']):7, len(i['ANDmat']:12
len(i['W_a']):5, len(i['ANDmat']:10
len(i['W_a']):9, len(i['ANDmat']:21
len(i['W_a']):9, len(i['ANDmat']:17
len(i['W_a']):8, len(i['ANDmat']:16
len(i['W_a']):9, len(i['ANDmat']:19
len(i['W_a']):8, len(i['ANDmat']:15
len(i['W_a']):9, len(i['ANDmat']:18
len(i['W_a']):9, len(i['ANDmat']:20
len(i['W_a']):9, len(i['ANDmat']:22
len(i['W_a']):6, len(i['ANDmat']:13
len(i['W_a']):8, len(i['ANDmat']:15
len(i['W_a']):9, len(i['ANDm

In [65]:
for i in X:
    for j in i['W_o']:
        print(j)
    print("len(i['W_o']):" + str(len(i['W_o'])) + "\n i['W_o']:" + str(i['W_o']) + "\n i['ANDmat']:" + str(i['ANDmat']))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 1]]
[[1 0]
 [0 1]]
[[1]]
[[1 0]
 [0 1]]
[[1]]
[[1]]
len(i['W_o']):9
 i['W_o']:[array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1]], dtype=int8)]
 i['ANDmat']:[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0

 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 1]]
[[1 0]
 [0 1]]
[[1]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0]
 [0 1]]
len(i['W_o']):9
 i['W_o']:[array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8)]
 i['ANDmat']:[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0

[[1 1]]
[[1]]
[[1]]
[[1]]
len(i['W_o']):7
 i['W_o']:[array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1]], dtype=int8), array([[1]], dtype=int8), array([[1]], dtype=int8)]
 i['ANDmat']:[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 1]]
[[1]]
[[1]]
[[1]]
[[1]]
len(i['W_o']):8
 i['W_o']:[array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
 

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
len(i['W_o']):8
 i['W_o']:[array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8)]
 i['ANDmat']:[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0

[[1]]
[[1 0]
 [0 1]]
[[1 1]]
[[1]]
[[1]]
[[1 0]
 [0 1]]
[[1 0]
 [0 1]]
len(i['W_o']):8
 i['W_o']:[array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8)]
 i['ANDmat']:[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 1]]
[[1 0]
 [0 1]]
[[1]]
[[1 0]
 [0 1]]
[[1 0 0]
 [0 

In [73]:
# W_o
# W_a
# ANDmat
# ORmat
for i in X:
    #for j in i['W_o']:
        #print(j)
    print("len(i['W_o']):" + str(len(i['W_o'])) + "\n i['W_a']:" + str(len(i['W_a'])) + "\n i['ORmat']:" + str(len(i['ORmat'])) +  "\n i['ANDmat']:" + str(len(i['ANDmat'])))
    print("i['W_o']:" + str(i['W_o']) + "\n i['W_a']:" + str(i['W_a']) + "\n i['ORmat']:" + str(i['ORmat']) +  "\n i['ANDmat']:" + str(i['ANDmat']))

len(i['W_o']):9
 i['W_a']:9
 i['ORmat']:18
 i['ANDmat']:16
i['W_o']:[array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1]], dtype=int8)]
 i['W_a']:[array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 0]], dtype=int8), array([[0, 1, 0, 0, 1, 0]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8), array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int8), array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]]
len(i['W_o']):9
 i['W_a']:9
 i['ORmat']:20
 i['ANDmat']:18
i['W_o']:[array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8)]
 i['W_a']:[array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1]], dtype=int8), array([[0, 1, 0, 0, 1, 0, 0]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8), array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1]], dtype=int8), array([[0, 0, 0, 0, 1, 0, 0,

 [0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0]]
len(i['W_o']):9
 i['W_a']:9
 i['ORmat']:23
 i['ANDmat']:21
i['W_o']:[array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1]], dtype=int8)]
 i['W_a']:[array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1]], dtype=int8), array([[0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int8), array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0

 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0]]
len(i['W_o']):6
 i['W_a']:6
 i['ORmat']:17
 i['ANDmat']:15
i['W_o']:[array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int8), array([[1, 0],
       [0, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1, 1]], dtype=int8), array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8), array([[1]], dtype=int8)]
 i['W_a']:[array([[1, 0, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1]], dtype=int8), array([[0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0]], dtype=int8), array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int8), array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1]], dtype=int8), a

In [88]:
# W_o
# W_a
# ANDmat
# ORmat
for i in X:
    #print( "i['ORmat']:\n" + str(i['ORmat']) +  "\n i['ANDmat']:\n" + str(i['ANDmat']) + "\n")
    print( "len of cols i['ORmat']:" + str(len(i['ORmat'])) +  " len of cols i['ANDmat']:" + str(len(i['ANDmat'])))
    print( "len of rows i['ORmat']:" + str(len(i['ORmat'][0])) +  " len of rows i['ANDmat']:" + str(len(i['ANDmat'][0])))
    
    print( "len of cols i['ORmat']:" + str(len(i['ORmat'])) +  " len of rows i['ORmat']:" + str(len(i['ORmat'][0])))
    print( "len of cols i['ANDmat']:" + str(len(i['ANDmat'])) +  " len of rows i['ANDmat']:" + str(len(i['ANDmat'][0])) + '\n')
    


len of cols i['ORmat']:18 len of cols i['ANDmat']:16
len of rows i['ORmat']:16 len of rows i['ANDmat']:18
len of cols i['ORmat']:18 len of rows i['ORmat']:16
len of cols i['ANDmat']:16 len of rows i['ANDmat']:18

len of cols i['ORmat']:19 len of cols i['ANDmat']:18
len of rows i['ORmat']:18 len of rows i['ANDmat']:19
len of cols i['ORmat']:19 len of rows i['ORmat']:18
len of cols i['ANDmat']:18 len of rows i['ANDmat']:19

len of cols i['ORmat']:19 len of cols i['ANDmat']:17
len of rows i['ORmat']:17 len of rows i['ANDmat']:19
len of cols i['ORmat']:19 len of rows i['ORmat']:17
len of cols i['ANDmat']:17 len of rows i['ANDmat']:19

len of cols i['ORmat']:23 len of cols i['ANDmat']:21
len of rows i['ORmat']:21 len of rows i['ANDmat']:23
len of cols i['ORmat']:23 len of rows i['ORmat']:21
len of cols i['ANDmat']:21 len of rows i['ANDmat']:23

len of cols i['ORmat']:15 len of cols i['ANDmat']:13
len of rows i['ORmat']:13 len of rows i['ANDmat']:15
len of cols i['ORmat']:15 len of rows i['O